# Nom de l'exécutable (à la fin du MakeFile)
TARGET_EXEC ?= BaseVersion

# Association des dossiers utilitaires: (création si nécessaire)
BUILD_DIR ?= ./build
TARGET_DIR ?= ./bin
SRC_DIRS ?= .

# Déclaration et attribution des variable
SRCS := $(shell find $(SRC_DIRS) -name "*.c") #recherche des sources (en .c)
OBJS := $(SRCS:%=$(BUILD_DIR)/%.o) # OBJS -> fichiers .o
DEPS := $(OBJS:.o=.d) # Dépendances

# Includes
INC_DIRS := $(shell find $(SRC_DIRS) -type d) # inclure les fichiers de dépendances
INC_FLAGS := $(addprefix -I,$(INC_DIRS)) # ajout de flags

# Flags
CFLAGS ?= $(INC_FLAGS) -MMD -MP -DNDEBUG -Wall -Wextra -Wno-unused-parameter

### L'ordre importe peu

# création de l'exécutable
$(TARGET_DIR)/$(TARGET_EXEC): $(OBJS)
		$(MKDIR_P) $(dir $@)
		$(CC) $(OBJS) -o $@ $(LDFLAGS)

# création des fichiers de dépendances
$(BUILD_DIR)/%.c.o: %.c
    	$(MKDIR_P) $(dir $@)
    	$(CC) $(CFLAGS) -c $< -o $@

# marquer clean comme commande à exécuter
.PHONY: clean
# suppression des dossiers utilitaires
clean:
	$(RM) -r $(BUILD_DIR) $(TARGET_DIR)

# assurer l'inclusion des dépendances
-include $(DEPS)

# ligne pour que le make puisse créer les dossiers
MKDIR_P ?= mkdir -p